{"level":"error"}
{"level":"error"}
{"level":"error","message":"Unable to create message: invalid messenger type ID"}
{"level":"error","message":"Unable to create message: invalid messenger type ID"}
{"level":"error","message":"Unable to create message: invalid messenger type ID"}
{"level":"error","message":"Unable to create message: invalid message type ID"}
{"level":"error","message":"Unable to create message: invalid message type ID"}
{"level":"error","message":"Unable to create message: invalid message type ID"}
{"level":"error"}
{"level":"error"}
{"level":"error"}
{"level":"error"}
{"level":"error","message":"error -> getaddrinfo ENOTFOUND pgdb","name":"SequelizeHostNotFoundError","original":{"code":"ENOTFOUND","errno":-3008,"hostname":"pgdb","syscall":"getaddrinfo"},"parent":{"code":"ENOTFOUND","errno":-3008,"hostname":"pgdb","syscall":"getaddrinfo"},"stack":"SequelizeHostNotFoundError: getaddrinfo ENOTFOUND pgdb\n    at Client._connectionCallback (/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:134:24)\n    at Client._handleErrorWhileConnecting (/app/node_modules/pg/lib/client.js:327:19)\n    at Client._handleErrorEvent (/app/node_modules/pg/lib/client.js:337:19)\n    at Connection.emit (node:events:513:28)\n    at Socket.reportStreamError (/app/node_modules/pg/lib/connection.js:58:12)\n    at Socket.emit (node:events:513:28)\n    at emitErrorNT (node:internal/streams/destroy:151:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)"}
{"level":"error","message":"Unable to initiate database: SequelizeHostNotFoundError: getaddrinfo ENOTFOUND pgdb"}
{"level":"error","message":"error -> getaddrinfo ENOTFOUND pgdb","name":"SequelizeHostNotFoundError","original":{"code":"ENOTFOUND","errno":-3008,"hostname":"pgdb","syscall":"getaddrinfo"},"parent":{"code":"ENOTFOUND","errno":-3008,"hostname":"pgdb","syscall":"getaddrinfo"},"stack":"SequelizeHostNotFoundError: getaddrinfo ENOTFOUND pgdb\n    at Client._connectionCallback (/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:134:24)\n    at Client._handleErrorWhileConnecting (/app/node_modules/pg/lib/client.js:327:19)\n    at Client._handleErrorEvent (/app/node_modules/pg/lib/client.js:337:19)\n    at Connection.emit (node:events:513:28)\n    at Socket.reportStreamError (/app/node_modules/pg/lib/connection.js:58:12)\n    at Socket.emit (node:events:513:28)\n    at emitErrorNT (node:internal/streams/destroy:151:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)"}
{"level":"error","message":"error -> getaddrinfo ENOTFOUND pgdb","name":"SequelizeHostNotFoundError","original":{"code":"ENOTFOUND","errno":-3008,"hostname":"pgdb","syscall":"getaddrinfo"},"parent":{"code":"ENOTFOUND","errno":-3008,"hostname":"pgdb","syscall":"getaddrinfo"},"stack":"SequelizeHostNotFoundError: getaddrinfo ENOTFOUND pgdb\n    at Client._connectionCallback (/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:134:24)\n    at Client._handleErrorWhileConnecting (/app/node_modules/pg/lib/client.js:327:19)\n    at Client._handleErrorEvent (/app/node_modules/pg/lib/client.js:337:19)\n    at Connection.emit (node:events:513:28)\n    at Socket.reportStreamError (/app/node_modules/pg/lib/connection.js:58:12)\n    at Socket.emit (node:events:513:28)\n    at emitErrorNT (node:internal/streams/destroy:151:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)"}
{"level":"error","message":"Unable to initiate database: SequelizeHostNotFoundError: getaddrinfo ENOTFOUND pgdb"}
{"level":"error","message":"error -> getaddrinfo ENOTFOUND pgdb","name":"SequelizeHostNotFoundError","original":{"code":"ENOTFOUND","errno":-3008,"hostname":"pgdb","syscall":"getaddrinfo"},"parent":{"code":"ENOTFOUND","errno":-3008,"hostname":"pgdb","syscall":"getaddrinfo"},"stack":"SequelizeHostNotFoundError: getaddrinfo ENOTFOUND pgdb\n    at Client._connectionCallback (/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:134:24)\n    at Client._handleErrorWhileConnecting (/app/node_modules/pg/lib/client.js:327:19)\n    at Client._handleErrorEvent (/app/node_modules/pg/lib/client.js:337:19)\n    at Connection.emit (node:events:513:28)\n    at Socket.reportStreamError (/app/node_modules/pg/lib/connection.js:58:12)\n    at Socket.emit (node:events:513:28)\n    at emitErrorNT (node:internal/streams/destroy:151:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)"}
{"level":"error","message":"Unable to initiate database: SequelizeDatabaseError: column \"actor_configuration_id\" of relation \"prompts\" contains null values"}
{"level":"error","message":"error ->","name":"SequelizeConnectionRefusedError","original":{"code":"ECONNREFUSED"},"parent":{"code":"ECONNREFUSED"},"stack":"SequelizeConnectionRefusedError\n    at Client._connectionCallback (/Volumes/Untitled/openai/divisor/server/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:131:24)\n    at Client._handleErrorWhileConnecting (/Volumes/Untitled/openai/divisor/server/node_modules/pg/lib/client.js:327:19)\n    at Client._handleErrorEvent (/Volumes/Untitled/openai/divisor/server/node_modules/pg/lib/client.js:337:19)\n    at Connection.emit (node:events:514:28)\n    at Socket.reportStreamError (/Volumes/Untitled/openai/divisor/server/node_modules/pg/lib/connection.js:58:12)\n    at Socket.emit (node:events:514:28)\n    at emitErrorNT (node:internal/streams/destroy:151:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)"}
{"level":"error","message":"error ->","name":"SequelizeConnectionRefusedError","original":{"code":"ECONNREFUSED"},"parent":{"code":"ECONNREFUSED"},"stack":"SequelizeConnectionRefusedError\n    at Client._connectionCallback (/Volumes/Untitled/openai/divisor/server/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:131:24)\n    at Client._handleErrorWhileConnecting (/Volumes/Untitled/openai/divisor/server/node_modules/pg/lib/client.js:327:19)\n    at Client._handleErrorEvent (/Volumes/Untitled/openai/divisor/server/node_modules/pg/lib/client.js:337:19)\n    at Connection.emit (node:events:514:28)\n    at Socket.reportStreamError (/Volumes/Untitled/openai/divisor/server/node_modules/pg/lib/connection.js:58:12)\n    at Socket.emit (node:events:514:28)\n    at emitErrorNT (node:internal/streams/destroy:151:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)"}
{"level":"error","message":"error ->","name":"SequelizeConnectionRefusedError","original":{"code":"ECONNREFUSED"},"parent":{"code":"ECONNREFUSED"},"stack":"SequelizeConnectionRefusedError\n    at Client._connectionCallback (/Volumes/Untitled/openai/divisor/server/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:131:24)\n    at Client._handleErrorWhileConnecting (/Volumes/Untitled/openai/divisor/server/node_modules/pg/lib/client.js:327:19)\n    at Client._handleErrorEvent (/Volumes/Untitled/openai/divisor/server/node_modules/pg/lib/client.js:337:19)\n    at Connection.emit (node:events:514:28)\n    at Socket.reportStreamError (/Volumes/Untitled/openai/divisor/server/node_modules/pg/lib/connection.js:58:12)\n    at Socket.emit (node:events:514:28)\n    at emitErrorNT (node:internal/streams/destroy:151:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)"}
{"level":"error","message":"Error: something wrong\n    at file:///app/routes/actors.js:175:19\n    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)\n    at next (/app/node_modules/express/lib/router/route.js:144:13)\n    at Route.dispatch (/app/node_modules/express/lib/router/route.js:114:3)\n    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)\n    at /app/node_modules/express/lib/router/index.js:284:15\n    at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)\n    at next (/app/node_modules/express/lib/router/index.js:280:10)\n    at Function.handle (/app/node_modules/express/lib/router/index.js:175:3)\n    at router (/app/node_modules/express/lib/router/index.js:47:12)"}
 (node:internal/streams/destroy:151:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)"}
{"level":"error","message":"error ->","name":"SequelizeConnectionRefusedError","original":{"code":"ECONNREFUSED"},"parent":{"code":"ECONNREFUSED"},"stack":"SequelizeConnectionRefusedError\n    at Client._connectionCallback (/Volumes/Untitled/openai/divisor/server/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:131:24)\n    at Client._handleErrorWhileConnecting (/Volumes/Untitled/openai/divisor/server/node_modules/pg/lib/client.js:327:19)\n    at Client._handleErrorEvent (/Volumes/Untitled/openai/divisor/server/node_modules/pg/lib/client.js:337:19)\n    at Connection.emit (node:events:514:28)\n    at Socket.reportStreamError (/Volumes/Untitled/openai/divisor/server/node_modules/pg/lib/connection.js:58:12)\n    at Socket.emit (node:events:514:28)\n    at emitErrorNT (node:internal/streams/destroy:151:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)"}
{"level":"error","message":"error -> connect ECONNREFUSED 172.19.0.2:5432","name":"SequelizeConnectionRefusedError","original":{"address":"172.19.0.2","code":"ECONNREFUSED","errno":-111,"port":5432,"syscall":"connect"},"parent":{"address":"172.19.0.2","code":"ECONNREFUSED","errno":-111,"port":5432,"syscall":"connect"},"stack":"SequelizeConnectionRefusedError: connect ECONNREFUSED 172.19.0.2:5432\n    at Client._connectionCallback (/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:131:24)\n    at Client._handleErrorWhileConnecting (/app/node_modules/pg/lib/client.js:327:19)\n    at Client._handleErrorEvent (/app/node_modules/pg/lib/client.js:337:19)\n    at Connection.emit (node:events:513:28)\n    at Socket.reportStreamError (/app/node_modules/pg/lib/connection.js:58:12)\n    at Socket.emit (node:events:513:28)\n    at emitErrorNT (node:internal/streams/destroy:151:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)"}
{"level":"error","message":"Unable to create message: invalid messenger ID"}
{"level":"error","message":"Error: Multipart: Boundary not found\n    at new Multipart (/app/node_modules/busboy/lib/types/multipart.js:233:13)\n    at getInstance (/app/node_modules/busboy/lib/index.js:33:12)\n    at module.exports (/app/node_modules/busboy/lib/index.js:56:10)\n    at multerMiddleware (/app/node_modules/multer/lib/make-middleware.js:28:16)\n    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)\n    at next (/app/node_modules/express/lib/router/route.js:144:13)\n    at Route.dispatch (/app/node_modules/express/lib/router/route.js:114:3)\n    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)\n    at /app/node_modules/express/lib/router/index.js:284:15\n    at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)"}
